server:
  servlet:
    context-path: /users/v1
  port: 50020

eureka:
  client:
    service-url:
      defaultZone: http://localhost:50002/eureka

spring:
  datasource:
    url: jdbc:mysql://localhost:50010/bdd-users
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

application:
  security:
    jwt:
      secret-key: gyv/HJqSzBR0sdzwrD66f9mvQkUo1R1eBwzW54I0S+Y=
      expiration: 3600000

logging:
  level:
    org:
      springframework:
        security: DEBUG